### ISSUE TITLE
mongodb stopped starting

### ISSUE THREAD

**Issue by lavaux** [wekan/wekan-snap#115]
The last refresh of the last 3 days caused the snap wekan that was running without trouble for the last 4 months to stop working.

It seems there is a conflict for the setup of MONGO_URL between the mongodb instance and the wekan instance. I could fix one or the other by setting the appropriate wekan variable but not both at the same time.

The error is the following:
2020-01-05T15:43:03Z wekan.wekan[2903686]: MONGO_URL=mongodb:///var/snap/wekan/current/share/mongodb-27019.sock/wekan
2020-01-05T15:43:04Z wekan.wekan[2903686]: /snap/wekan/698/programs/server/node_modules/fibers/future.js:280
2020-01-05T15:43:04Z wekan.wekan[2903686]: 						throw(ex);
2020-01-05T15:43:04Z wekan.wekan[2903686]: 						^
2020-01-05T15:43:04Z wekan.wekan[2903686]: MongoParseError: No hostname or hostnames provided in connection string
2020-01-05T15:43:04Z wekan.wekan[2903686]:     at parseConnectionString (/snap/wekan/698/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/uri_parser.js:607:21)
2020-01-05T15:43:04Z wekan.wekan[2903686]:     at connect (/snap/wekan/698/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/mongo_client_ops.js:195:3)
2020-01-05T15:43:04Z wekan.wekan[2903686]:     at connectOp (/snap/wekan/698/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/mongo_client_ops.js:284:3)
2020-01-05T15:43:04Z wekan.wekan[2903686]:     at executeOperation (/snap/wekan/698/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:416:24)
2020-01-05T15:43:04Z wekan.wekan[2903686]:     at MongoClient.connect (/snap/wekan/698/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:175:10)
2020-01-05T15:43:04Z wekan.wekan[2903686]:     at Function.MongoClient.connect (/snap/wekan/698/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:341:22)
2020-01-05T15:43:04Z wekan.wekan[2903686]:     at new MongoConnection (packages/mongo/mongo_driver.js:177:11)
2020-01-05T15:43:04Z wekan.wekan[2903686]:     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
2020-01-05T15:43:04Z wekan.wekan[2903686]:     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
2020-01-05T15:43:04Z wekan.wekan[2903686]:     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
2020-01-05T15:43:04Z wekan.wekan[2903686]:     at new Collection (packages/mongo/collection.js:97:40)
2020-01-05T15:43:04Z wekan.wekan[2903686]:     at packages/idmontie_migrations.js:38:15
2020-01-05T15:43:04Z wekan.wekan[2903686]:     at packages/idmontie_migrations.js:255:4
2020-01-05T15:43:04Z wekan.wekan[2903686]:     at packages/idmontie_migrations.js:263:3
2020-01-05T15:43:04Z wekan.wekan[2903686]:     at /snap/wekan/698/programs/server/boot.js:398:38
2020-01-05T15:43:04Z wekan.wekan[2903686]:     at Array.forEach (<anonymous>)
2020-01-05T15:43:04Z systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, status=1/FAILURE
2020-01-05T15:43:04Z systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.

fixing MONGO_URL to something with a hostname will clear up that error but create another one when starting mongodb itself.

**Comment by xet7** [comment]
Try:
```
sudo snap unset wekan SOME-SETTING-HERE
```

**Comment by lavaux** [comment]
no, it did not work.


The only solution that I have found is to install a separate mongodb 
instance and ask the wekan in snap package to use it.

**Comment by xet7** [comment]
@lavaux 

You could try to reinstall Wekan:
https://github.com/wekan/wekan-snap/issues/103#issuecomment-571064587

Some future Snap version will probably upgrade mongodb version if older ones become incompatible with newest Meteor/Node.

**Comment by xet7** [comment]
@lavaux 

What are your current Snap settings? Please anonymize urls/passwords before posting.
```
sudo snap get wekan
```

**Comment by xet7** [comment]
For example, locally I have these settings:
```
$ sudo snap get wekan
Key                         Value
caddy-enabled               false
mongodb-bind-ip             127.0.0.1
port                        2000
richer-card-comment-editor  false
root-url                    http://192.168.0.100:2000
```
At server, I have these settings:
```
$ snap get wekan
Key                     Value
caddy-enabled  true
port                    3001
root-url                https://boards.example.com
```
At `/var/snap/wekan/common/Caddyfile` are these settings:
```
https://boards.example.com {
        tls {
            alpn http/1.1
        }

        proxy / localhost:3001 {
          websocket
          transparent
        }
}
```

**Comment by xet7** [comment]
Alternative Caddyfile with [CloudFlare](https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config) or other SSL certs (no Let's Encrypt certs)
```
http://boards.example.com https://boards.example.com {
        tls {
            load /var/snap/wekan/common/certificates
            alpn http/1.1
        }

        proxy / localhost:3001 {
          websocket
          transparent
        }
}
```

**Comment by lavaux** [comment]
$ sudo snap get wekan

Key                       Value
debug                     false
disable-mongodb           true
mail-from                 webaquila@iap.fr
mail-url                  smtp://smtp.iap.fr:25
mongo-url                 mongodb://127.0.0.1:27021/wekan
mongodb-bind-unix-socket  nill
mongodb-port              27021
port                      3001
root-url                  https://www.aquila-consortium.org/wekan


The server is behind a reverse proxy. But the problem is not with the 
Caddyfile. It is starting the mongodb instance and getting wekan to talk 
to that server. Something changed with the snap package after December 
30th 2019. Previous configuration was perfectly running.

I had to set the mongo-url in the above to access the outside instance.

**Comment by xet7** [comment]
@lavaux 

What Linux version are you running? Have you installed latest apt/yum updates?

Are you running at some platform that has limited kernel, like OpenVZ/OVH/Kimsufi ?

I don't currently have any problem installing Wekan on newest Ubuntu and Debian 64bit.

**Comment by lavaux** [comment]
I am not running on limited platform. It is a full baremetal server that 
I physically control running Fedora 31.

The problem is that the mongodb in the snap is failing to start if I do 
not set mongodb-bind-unix-socket to something sane:

Jan 07 07:46:51 athos.iap.fr mongod.27021[3589545]: [initandlisten] 
build environment:
Jan 07 07:46:51 athos.iap.fr mongod.27021[3589545]: [initandlisten]     
distmod: ubuntu1604
Jan 07 07:46:51 athos.iap.fr mongod.27021[3589545]: [initandlisten]     
distarch: x86_64
Jan 07 07:46:51 athos.iap.fr mongod.27021[3589545]: [initandlisten]     
target_arch: x86_64
Jan 07 07:46:51 athos.iap.fr mongod.27021[3589545]: [initandlisten] 
options: { net: { bindIp: "127.0.0.1", port: 27021 }, storage: { dbPath: 
"/var/snap/wekan/comm>

Jan 07 07:46:51 athos.iap.fr mongod.27021[3589545]: [initandlisten] 
listen(): bind() failed errno:2 No such file or directory for socket: 
/tmp/mongodb-27021.sock
Jan 07 07:46:51 athos.iap.fr mongod.27021[3589545]: [initandlisten] 
Failed to set up sockets during startup.


So I tried a fresh install on a different computer (also running Fedora 
31). The fresh install was running ok (I do not know why there is not 
the above error). But if I set with 'snap set wekan 
mongodb-bind-unix-socket=/var/snap/wekan/current/share' then, I get the 
following error (on a freshly installed and working snap wekan):

2020-01-07T06:55:01Z wekan.wekan[21051]: 
MONGO_URL=mongodb:///var/snap/wekan/current/share/mongodb-27019.sock/wekan
2020-01-07T06:55:01Z wekan.wekan[21051]: 
/snap/wekan/714/programs/server/node_modules/fibers/future.js:280
2020-01-07T06:55:01Z wekan.wekan[21051]: throw(ex);
2020-01-07T06:55:01Z wekan.wekan[21051]: ^
2020-01-07T06:55:01Z wekan.wekan[21051]: MongoParseError: No hostname or 
hostnames provided in connection string
2020-01-07T06:55:01Z wekan.wekan[21051]:     at parseConnectionString 
(/snap/wekan/714/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/uri_parser.js:607:21)
2020-01-07T06:55:01Z wekan.wekan[21051]:     at connect 
(/snap/wekan/714/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/mongo_client_ops.js:195:3)
2020-01-07T06:55:01Z wekan.wekan[21051]:     at connectOp 
(/snap/wekan/714/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/mongo_client_ops.js:284:3)
2020-01-07T06:55:01Z wekan.wekan[21051]:     at executeOperation 
(/snap/wekan/714/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:416:24)
2020-01-07T06:55:01Z wekan.wekan[21051]:     at MongoClient.connect 
(/snap/wekan/714/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:175:10)
2020-01-07T06:55:01Z wekan.wekan[21051]:     at 
Function.MongoClient.connect 
(/snap/wekan/714/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongod

**Comment by xet7** [comment]
Moved to #103
