### ISSUE TITLE
LDAP sync issue

### ISSUE THREAD

**Issue by y0d4a** [wekan/wekan-snap#122]
Hi, 
i using wekan so far for 2 years, and great work!
Now i see that there is ldap integration which is great!
but have issue with sync..
error log say:

>  [INFO] Enabling LDAP Background Sync
Apr 28 00:49:40 uxwekan wekan.wekan[30113]: Exception in callback of async function: TypeError: str.toLowerCase is not a function
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at Object.later.parse.text (/snap/wekan/807/programs/server/npm/node_modules/meteor/percolate_synced-cron/node_modules/later/later.js:1506:34)
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at Object.schedule (packages/wekan-ldap/server/sync.js:436:22)
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at scheduleEntry (packages/percolate_synced-cron.js:126:24)
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at packages/percolate_synced-cron.js:163:7
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at Function._.each._.forEach (packages/underscore.js:147:22)
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at packages/percolate_synced-cron.js:162:7
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at Object.startup (packages/meteor.js:992:5)
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at Object.SyncedCron.start (packages/percolate_synced-cron.js:160:10)
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at addCronJobDebounced (packages/wekan-ldap/server/sync.js:445:6)
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at runWithEnvironment (packages/meteor.js:1286:24)
Apr 28 00:49:40 uxwekan wekan.wekan[30113]: Exception in callback of async function: TypeError: str.toLowerCase is not a function
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at Object.later.parse.text (/snap/wekan/807/programs/server/npm/node_modules/meteor/percolate_synced-cron/node_modules/later/later.js:1506:34)
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at Object.schedule (packages/wekan-ldap/server/sync.js:436:22)
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at scheduleEntry (packages/percolate_synced-cron.js:126:24)
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at packages/percolate_synced-cron.js:163:7
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at Function._.each._.forEach (packages/underscore.js:147:22)
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at packages/percolate_synced-cron.js:162:7
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at Object.startup (packages/meteor.js:992:5)
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at Object.SyncedCron.start (packages/percolate_synced-cron.js:160:10)
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at notificationCleanupDebounced (models/users.js:1003:16)
Apr 28 00:49:40 uxwekan wekan.wekan[30113]:     at runWithEnvironment (packages/meteor.js:1286:24)
Apr 28 00:50:09 uxwekan wekan.wekan[30113]: (node:31468) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Apr 28 00:50:13 uxwekan wekan.wekan[30113]: [INFO] Init LDAP login "XXX"
Apr 28 00:50:13 uxwekan wekan.wekan[30113]: [WARN] Lookup for unset variable: INTERNAL_LOG_LEVEL
Apr 28 00:50:13 uxwekan wekan.wekan[30113]: [WARN] Lookup for unset variable: LDAP_USER_ATTRIBUTES
Apr 28 00:50:13 uxwekan wekan.wekan[30113]: [INFO] Init setup
Apr 28 00:50:13 uxwekan wekan.wekan[30113]: [INFO] Connecting "ldap://X.X.X.X:389"
Apr 28 00:50:13 uxwekan wekan.wekan[30113]: [DEBUG] connectionOptions{
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:   url: 'ldap://X.X.X.X:389',
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:   timeout: 10000,
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:   connectTimeout: 10000,
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:   idleTimeout: 10000,
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:   reconnect: true,
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:   log: Logger {
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:     _events: [Object: null prototype] {},
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:     _eventsCount: 0,
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:     _maxListeners: undefined,
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:     _level: 30,
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:     streams: [ [Object] ],
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:     serializers: null,
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:     src: false,
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:     fields: {
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:       name: 'ldapjs',
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:       component: 'client',
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:       hostname: 'wekan',
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:       pid: 31468
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:     },
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:     [Symbol(kCapture)]: false
Apr 28 00:50:13 uxwekan wekan.wekan[30113]:   }
Apr 28 00:50:13 uxwekan wekan.wekan[30113]: }
Apr 28 00:50:14 uxwekan wekan.wekan[30113]: [INFO] LDAP connected
Apr 28 00:50:14 uxwekan wekan.wekan[30113]: [INFO] Binding UserDN "CN=XXX,OU=Service Accounts,DC=topnet,DC=rs"
Apr 28 00:50:14 uxwekan wekan.wekan[30113]: [ERROR] InvalidCredentialsError: 80090308: LdapErr: DSID-0C090446, comment: AcceptSecurityContext error, data 52e, v2580
Apr 28 00:50:14 uxwekan wekan.wekan[30113]:
Apr 28 00:50:24 uxwekan wekan.wekan[30113]: [INFO] Idle
Apr 28 00:50:24 uxwekan wekan.wekan[30113]: [INFO] Disconecting
> 

i try to enter password in both way:
snap set wekan ldap-authentication-password='<123>'
snap set wekan ldap-authentication-password='123'

but in every combination he said wrong creds. but creds. are fine...

can i get some help? :)

p.s: i do set like in this post: https://github.com/wekan/wekan/wiki/LDAP
with snap

tnx.

**Comment by y0d4a** [comment]
hm, ok i found mistake.
now i have new issue, that he always try to create existing user when he try to login?

> Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [INFO] LDAP connected
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [INFO] Binding UserDN "CN=X,OU=Service Accounts,DC=X,DC=X"
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [INFO] Searching user "X"
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [DEBUG] searchOptions {
Apr 28 19:00:36 uxwekan wekan.wekan[19066]:   "filter": "(&(sAMAccountName=X))",
Apr 28 19:00:36 uxwekan wekan.wekan[19066]:   "scope": "sub",
Apr 28 19:00:36 uxwekan wekan.wekan[19066]:   "sizeLimit": 0
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: }
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [DEBUG] BaseDN "DC=X,DC=X"
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [INFO] Search result count 1
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [INFO] Authenticating "CN=X"
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [INFO] Authenticated "CN=X"
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [DEBUG] Identifying user with: sAMAccountName
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [INFO] Querying user
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [DEBUG] userQuery {
Apr 28 19:00:36 uxwekan wekan.wekan[19066]:   "services.ldap.id": "727379306434"
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: }
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [DEBUG] userQuery {
Apr 28 19:00:36 uxwekan wekan.wekan[19066]:   "username": "XXX"
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: }
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [INFO] User does not exist, creating "XXX"
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [DEBUG] Identifying user with: sAMAccountName
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [DEBUG] Identifying user with: sAMAccountName
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [DEBUG] New user data {
Apr 28 19:00:36 uxwekan wekan.wekan[19066]:   "username": "XX",
Apr 28 19:00:36 uxwekan wekan.wekan[19066]:   "email": "XX@XXX.XX"
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: }
Apr 28 19:00:36 uxwekan wekan.wekan[19066]: [ERROR] Error creating user {
Apr 28 19:00:36 uxwekan wekan.wekan[19066]:   "isClientSafe": true,
Apr 28 19:00:36 uxwekan wekan.wekan[19066]:   "error": 403,
Apr 28 19:00:36 uxwekan wekan.wekan[19066]:   "reason": "Email already exists.",
Apr 28 19:00:36 uxwekan wekan.wekan[19066]:   "message": "Email already exists. [403]",
Apr 28 19:00:36 uxwekan wekan.wekan[19066]:   "errorType": "Meteor.Error"

>

**Comment by y0d4a** [comment]
ah my fault again :)
problem was that i was try to login with AD user which have email address same as local user in wekan :)
now all is fine, great! and thank you for modul!
