### ISSUE TITLE
Unauthorized OAuth2.0 external authentication server

### ISSUE THREAD

**Issue by dfcarvajalf** [wekan/wekan-snap#127]
Hello, I am trying to configure authentication through OAuth2.0 with an external server and when trying to authenticate it gives me the following error:

2020-07-27T14:43:49Z wekan.wekan[12979]: {"line":"403","file":"oauth_server.js","message":"Error in OAuth Server: Failed to get token from OIDC https://www.-----.--/---/api/oauth/token: failed [401] {"timestamp":"2020-07-27T14:43:48.113+0000","status":401,"error":"Unauthorized","message":"Unauthorized","path":"/---/api/oauth/token"}","time":{"$date":1595861028211},"level":"warn"}
2020-07-27T14:43:49Z wekan.wekan[12979]: Exception while invoking method 'login' Error: Failed to get token from OIDC https://www.-----.--/---/api/oauth/token: failed [401] {"timestamp":"2020-07-27T14:43:48.113+0000","status":401,"error":"Unauthorized","message":"Unauthorized","path":"/---/api/oauth/token"}
2020-07-27T14:43:49Z wekan.wekan[12979]: at getToken (packages/wekan-oidc.js:104:20)
2020-07-27T14:43:49Z wekan.wekan[12979]: at Object.handleOauthRequest (packages/wekan-oidc.js:29:15)
2020-07-27T14:43:49Z wekan.wekan[12979]: at OAuth._requestHandlers. (packages/oauth2/oauth2_server.js:10:33)
2020-07-27T14:43:49Z wekan.wekan[12979]: at middleware (packages/oauth/oauth_server.js:170:5)
2020-07-27T14:43:49Z wekan.wekan[12979]: at /snap/wekan/944/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

Is it a wekan or server error?

What I can do?

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/3224
