### ISSUE TITLE
Wekan 4.56 fails to start

### ISSUE THREAD

**Issue by killua-eu** [wekan/wekan-snap#140]
Hi,

I noticed that wekan fell away, possibly after a refresh? I was tracking the stable channel, then retried with latest/edge, with the same result

```
channels:
  latest/stable:    4.56             2020-11-30 (1119) 164MB -
  latest/candidate: 4.56             2020-11-30 (1119) 164MB -
  latest/beta:      4.56             2020-11-30 (1119) 164MB -
  latest/edge:      4.56-16-g62f6cc7 2020-12-03 (1128) 164MB -
  installed:          4.56-16-g62f6cc7            (1128) 164MB -
```

here the error

```
2020-12-03T16:24:40Z wekan.wekan[12777]: {"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Thu Dec 03 2020 16:24:40 GMT+0000 (Coordinated Universal Time)","time":{"$date":1607012680712},"level":"info"}
root@az01-wekan:~# journalctl -r
-- Logs begin at Sat 2020-07-04 19:59:02 UTC, end at Thu 2020-12-03 16:24:40 UTC. --
Dec 03 16:24:40 az01-wekan wekan.wekan[12777]: {"line":"87","file":"percolate_synced-cron.js","message":"
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]: Presence started serverId=eNajiE7HFTaNbY735
Dec 03 16:24:38 az01-wekan systemd-journald[52]: Forwarding to syslog missed 5 messages.
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]: }
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]:   code: 'ENOENT'
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]:   syscall: 'open',
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]:   errno: -2,
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]:     at /snap/wekan/1128/programs/server/boot.js:463:13 {
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]:     at Function.run (/snap/wekan/1128/programs/server/prof
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]:     at /snap/wekan/1128/programs/server/boot.js:464:7
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]:     at /snap/wekan/1128/programs/server/boot.js:226:21
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]:     at Array.forEach (<anonymous>)
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]:     at /snap/wekan/1128/programs/server/boot.js:401:38
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]:     at packages/wekan-oidc.js:285:3
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]:     at packages/wekan-oidc.js:277:4
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]:     at packages/wekan-oidc.js:30:14
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]:     at Object.readFileSync (fs.js:364:35)
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]:     at Object.openSync (fs.js:462:3)
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]: Error: ENOENT: no such file or directory, open
Dec 03 16:24:38 az01-wekan wekan.wekan[12777]: WARNING: failed loading:
Dec 03 16:24:36 az01-wekan wekan.wekan[12777]: MONGO_URL=mongodb://127.0.0.1:27019/wekan
Dec 03 16:24:36 az01-wekan wekan.wekan[12777]: ORACLE_OIM_ENABLED=false (default value)
Dec 03 16:24:36 az01-wekan wekan.wekan[12777]: SAML_ATTRIBUTES= (default value)
```

any idea what's wrong? thanks lots, Pavel

**Comment by xet7** [comment]
You can change back to stable with:
```
sudo snap refresh wekan --stable --amend
```
And update snaps manually:
```
sudo snap refresh
```
Do you have root-url etc set correctly?
```
sudo snap get wekan
```
Does you Wekan work? For me, newest Wekan works.
