### ISSUE TITLE
Cannot create user 

### ISSUE THREAD

**Issue by tromlet** [wekan/wekan-snap#148]
| Component | Version |
|--|--|
| **Wekan Version** | 4.92.0 |
| **Meteor version** | 2.0 |
| **Node version** | 12.20.1 |
| **MongoDB version** | 3.2.22 |
| **MongoDB storage engine** | wiredTiger |
| **MongoDB Oplog enabled** |  |
| **OS Type** | Linux |
| **OS Platform** | linux |
| **OS Arch** | x64 |
| **OS Release** | 3.10.0-1160.11.1.el7.x86_64 |
| **OS Uptime** | 1 days, 2 hours, 55 minutes, 18 seconds |
| **OS Load Average** | 0.01, 0.03, 0.05 |
| **OS Total Memory** | 35 GB |
| **OS Free Memory** | 33 GB |
| **OS CPU Count** | 12 |

I am unable to create new users with a simple password, I get the following error in my WeKan log (`journalctl -xef -u snap.wekan.wekan`):
```log
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: Exception while invoking method 'setCreateUser' Error: Match error: Expected Array
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at check (packages/check/match.js:36:17)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at MethodInvocation.setCreateUser (models/users.js:816:9)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at packages/check/match.js:118:15
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at packages/ddp-server/livedata_server.js:719:19
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at packages/ddp-server/livedata_server.js:717:46
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at packages/ddp-server/livedata_server.js:715:46
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at new Promise (<anonymous>)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at Session.method (packages/ddp-server/livedata_server.js:689:23)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at packages/ddp-server/livedata_server.js:559:43
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at errorClass.<anonymous> (packages/check/match.js:91:27)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at new errorClass (packages/meteor.js:655:17)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at check (packages/check/match.js:36:17)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at MethodInvocation.setCreateUser (models/users.js:816:9)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at packages/check/match.js:118:15
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at packages/ddp-server/livedata_server.js:719:19
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at packages/ddp-server/livedata_server.js:717:46
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at packages/ddp-server/livedata_server.js:715:46
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at new Promise (<anonymous>)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at Session.method (packages/ddp-server/livedata_server.js:689:23)
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: at packages/ddp-server/livedata_server.js:559:43 {
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: isClientSafe: true,
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: error: 400,
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: reason: 'Match failed',
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: details: undefined,
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: errorType: 'Meteor.Error'
Feb 10 12:00:00 wekan.example.com wekan.wekan[19347]: }
```

**Comment by tromlet** [comment]
Never mind. I see that it appears to have been fixed, hah: https://github.com/wekan/wekan/issues/3539

Will re-open this if updating does not fix the issue.
