### ISSUE TITLE
snap run wekan fails with "MongoError: failed to connect to server"

### ISSUE THREAD

**Issue by lofidevops** [wekan/wekan-snap#16]
````
~> sudo snap install wekan

~> snap run wekan

using default value: MONGODB_BIND_UNIX_SOCKET='/var/snap/wekan/76/share'
using default value: MONGODB_BIND_IP=''
using default value: MONGODB_PORT='27019'
using default value: MAIL_URL='smtp://user:pass@mailserver.examples.com:25/'
using default value: MAIL_FROM='wekan-admin@example.com'
using default value: ROOT_URL='http://127.0.0.1'
using default value: PORT='8080'
using default value: DISABLE_MONGODB='false'
MONGO_URL=mongodb:///var/snap/wekan/76/share/mongodb-27019.sock/wekan

/snap/wekan/76/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
MongoError: failed to connect to server [/var/snap/wekan/76/share/mongodb-27019.sock:27017] on first connect
    at Object.Future.wait (/snap/wekan/76/programs/server/node_modules/fibers/future.js:449:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:211:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Mongo.Collection (packages/mongo/collection.js:99:40)
    at packages/idmontie_migrations.js:38:15
    at packages/idmontie_migrations.js:255:4
    at packages/idmontie_migrations.js:267:3
    at /snap/wekan/76/programs/server/boot.js:303:34
    - - - - -
    at [object Object].<anonymous> (/snap/wekan/76/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at emitOne (events.js:77:13)
    at [object Object].emit (events.js:169:7)
    at [object Object].<anonymous> (/snap/wekan/76/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at [object Object].g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at [object Object].emit (events.js:172:7)
    at Socket.<anonymous> (/snap/wekan/76/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
````

Are there any other details I can provide?

**Comment by lofidevops** [comment]
Ah, it's already installed as services and running:

````
sudo systemctl status snap.wekan.mongodb
sudo systemctl status snap.wekan.wekan
````

...and accessible at http://127.0.0.1:8080
