### ISSUE TITLE
Snap doesn't start upon reboot

### ISSUE THREAD

**Issue by behemothwerecat** [wekan/wekan-snap#164]
After installing the snap and using Wekan once, the services have not been able to restart after a reboot. 

I'm running the snap locally on Debian bullseye:

`sudo snap get wekan`

```
Key       Value
port      8080
root-url  http://localhost:8080
```
I get the following output when wekan tries to start:
```
/snap/wekan/1998/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^

MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27019
    at Timeout._onTimeout (/snap/wekan/1998/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/sdam/topology.js:439:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map {
      '127.0.0.1:27019' => ServerDescription {
        address: '127.0.0.1:27019',
        error: Error: connect ECONNREFUSED 127.0.0.1:27019
            at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
          name: 'MongoNetworkError'
        },
        roundTripTime: -1,
        lastUpdateTime: 213330,
        lastWriteDate: null,
        opTime: null,
        type: 'Unknown',
        topologyVersion: undefined,
        minWireVersion: 0,
        maxWireVersion: 0,
        hosts: [],
        passives: [],
        arbiters: [],
        tags: []
      }
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
```
And when wekan.mongodb tries to start:
```
WAIT_SPINNER=Bounce (default value)
error: error running snapctl: get which option?
NODE_OPTIONS=--max_old_space_size=4096 (default value)
mongodb bind options:  --bind_ip 127.0.0.1 --port 27019
Sending mongodb logs to /dev/null
Error parsing command line: unrecognised option '--bind_ip'
try 'mongo --help' for more information
```

Any help would be very appreciated.

**Comment by behemothwerecat** [comment]
Duplicate because account was frozen until recently
