### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by GuiGuiSoft** [wekan/wekan-snap#50]
Hello,

I followed the installation step, so I installed the wekan snap and configured the following value.
```
# snap get wekan
Key       Value
port      80
root-url  http://10.6.64.74
```

However Wekan is not accessible. Even on the host machine a curl fail.
```
curl localhost
curl: (7) Failed to connect to localhost port 80: Connexion refusée
```

Finally a `netstat -laputen` does not show anything listening on port 80, 8080, or 3001.

Any advice ? Regards.

Edit: may be useful, `sudo tail -f /var/log/syslog` print the "looping" logs below :

```
[...]
Jun 27 15:17:15 ubuntu systemd[1]: Stopped Service for snap application wekan.wekan.
Jun 27 15:17:15 ubuntu systemd[1]: Started Service for snap application wekan.wekan.
Jun 27 15:17:16 ubuntu wekan.wekan[16222]: MONGODB_BIND_UNIX_SOCKET=/var/snap/wekan/219/share (default value)
Jun 27 15:17:16 ubuntu wekan.wekan[16222]: MONGODB_BIND_IP= (default value)
Jun 27 15:17:16 ubuntu wekan.wekan[16222]: MONGODB_PORT=27019 (default value)
Jun 27 15:17:16 ubuntu wekan.wekan[16222]: MAIL_URL=smtp://user:pass@mailserver.examples.com:25/ (default value)
Jun 27 15:17:16 ubuntu wekan.wekan[16222]: MAIL_FROM=wekan-admin@example.com (default value)
Jun 27 15:17:16 ubuntu wekan.wekan[16222]: ROOT_URL=http://10.6.64.74
Jun 27 15:17:16 ubuntu wekan.wekan[16222]: PORT=80
Jun 27 15:17:16 ubuntu wekan.wekan[16222]: DISABLE_MONGODB=false (default value)
Jun 27 15:17:16 ubuntu wekan.wekan[16222]: CADDY_ENABLED=false (default value)
Jun 27 15:17:16 ubuntu wekan.wekan[16222]: CADDY_BIND_PORT=3001 (default value)
Jun 27 15:17:16 ubuntu wekan.wekan[16222]: MONGO_URL=mongodb:///var/snap/wekan/219/share/mongodb-27019.sock/wekan
Jun 27 15:17:17 ubuntu wekan.wekan[16222]: Presence started serverId=u7gFMLf4wf7SsCigL
Jun 27 15:17:17 ubuntu wekan.wekan[16222]: Note: you are using a pure-JavaScript implementation of bcrypt.
Jun 27 15:17:17 ubuntu wekan.wekan[16222]: While this implementation will work correctly, it is known to be
Jun 27 15:17:17 ubuntu wekan.wekan[16222]: approximately three times slower than the native implementation.
Jun 27 15:17:17 ubuntu wekan.wekan[16222]: In order to use the native implementation instead, run
Jun 27 15:17:17 ubuntu wekan.wekan[16222]:   meteor npm install --save bcrypt
Jun 27 15:17:17 ubuntu wekan.wekan[16222]: in the root directory of your application.
Jun 27 15:17:17 ubuntu wekan.wekan[16222]: > Starting change-attachments-type-for-non-images migration.
Jun 27 15:17:18 ubuntu wekan.wekan[16222]: /snap/wekan/219/programs/server/node_modules/fibers/future.js:280
Jun 27 15:17:18 ubuntu wekan.wekan[16222]: #011#011#011#011#011#011throw(ex);
Jun 27 15:17:18 ubuntu wekan.wekan[16222]: #011#011#011#011#011#011^
Jun 27 15:17:18 ubuntu wekan.wekan[16222]: TypeError: Attachments.forEach is not a function
Jun 27 15:17:18 ubuntu wekan.wekan[16222]:     at Object.Migrations.add [as migrationCallback] (server/migrations.js:58:15)
Jun 27 15:17:18 ubuntu wekan.wekan[16222]:     at packages/idmontie_migrations.js:238:17
Jun 27 15:17:18 ubuntu wekan.wekan[16222]:     at Function.time (/snap/wekan/219/programs/server/profile.js:309:28)
Jun 27 15:17:18 ubuntu wekan.wekan[16222]:     at /snap/wekan/219/programs/server/boot.js:423:13
Jun 27 15:17:18 ubuntu wekan.wekan[16222]:     at /snap/wekan/219/programs/server/boot.js:464:5
Jun 27 15:17:18 ubuntu wekan.wekan[16222]:     at Function.run (/snap/wekan/219/programs/server/profile.js:510:12)
Jun 27 15:17:18 ubuntu wekan.wekan[16222]:     at /snap/wekan/219/programs/server/boot.js:462:11
Jun 27 15:17:18 ubuntu systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, status=1/FAILURE
Jun 27 15:17:18 ubuntu systemd[1]: snap.wekan.wekan.service: Unit entered failed state.
Jun 27 15:17:18 ubuntu systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
Jun 27 15:17:18 ubuntu systemd[1]: snap.wekan.wekan.service: Service hold-off time over, scheduling restart.
Jun 27 15:17:18 ubuntu systemd[1]: Stopped Service for snap application wekan.wekan.
Jun 27 15:17:18 ubuntu systemd[1]: Started Service for snap application wekan.wekan.
[...]
```

**Comment by whynotlinux** [comment]
I have exactly the same problem on debian 9

**Comment by GuiGuiSoft** [comment]
Hello, As the snap has been refreshed (1.10 ?). Here is the new log for 

Edit : I edited the log because I tried so many things that the root-url parameter was not good anymore. Moreover I closed the issue, whereas I did not want to.
Edit 2 : IT WORKS ! \o/ (so I close again... :innocent: ) I get the snap update did the job

```
[...]
Jun 28 18:59:24 ubuntu kernel: [  679.106993] audit: type=1400 audit(1530205164.164:79): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap-update-ns.wekan" pid=5953 comm="apparmor_parser"
Jun 28 18:59:24 ubuntu kernel: [  679.246519] audit: type=1400 audit(1530205164.304:80): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap.wekan.caddy" pid=5955 comm="apparmor_parser"
Jun 28 18:59:24 ubuntu kernel: [  679.391077] audit: type=1400 audit(1530205164.448:81): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap.wekan.database-backup" pid=5957 comm="apparmor_parser"
Jun 28 18:59:24 ubuntu kernel: [  679.483689] audit: type=1400 audit(1530205164.540:82): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap.wekan.database-list-backups" pid=5959 comm="apparmor_parser"
Jun 28 18:59:24 ubuntu kernel: [  679.605254] audit: type=1400 audit(1530205164.660:83): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap.wekan.database-restore" pid=5961 comm="apparmor_parser"
Jun 28 18:59:24 ubuntu kernel: [  679.695207] audit: type=1400 audit(1530205164.752:84): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap.wekan.help" pid=5963 comm="apparmor_parser"
Jun 28 18:59:24 ubuntu kernel: [  679.816487] audit: type=1400 audit(1530205164.872:85): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap.wekan.hook.configure" pid=5965 comm="apparmor_parser"
Jun 28 18:59:24 ubuntu kernel: [  679.906535] audit: type=1400 audit(1530205164.964:86): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap.wekan.hook.install" pid=5967 comm="apparmor_parser"
Jun 28 18:59:25 ubuntu kernel: [  679.999196] audit: type=1400 audit(1530205165.056:87): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap.wekan.hook.post-refresh" pid=5969 comm="apparmor_parser"
Jun 28 18:59:25 ubuntu kernel: [  680.121907] audit: type=1400 audit(1530205165.180:88): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap.wekan.mongodb" pid=5971 comm="apparmor_parser"
Jun 28 18:59:28 ubuntu systemd[1]: Reloading.
Jun 28 18:59:28 ubuntu systemd[1]: Started ACPI event daemon.
Jun 28 18:59:28 ubuntu systemd[1]: Reloading.
Jun 28 18:59:29 ubuntu systemd[1]: Started ACPI event daemon.
Jun 28 18:59:29 ubuntu systemd[1]: Reloading.
Jun 28 18:59:29 ubuntu systemd[1]: Started ACPI event daemon.
Jun 28 18:59:29 ubuntu systemd[1]: Reloading.
Jun 28 18:59:29 ubuntu systemd[1]: Started ACPI event daemon.
Jun 28 18:59:30 ubuntu systemd[1]: Started Service for snap application wekan.caddy.
Jun 28 18:59:30 ubuntu systemd[1]: Started Service for snap application wekan.mongodb.
Jun 28 18:59:30 ubuntu systemd[1]: Started Service for snap application wekan.wekan.
Jun 28 18:59:30 ubuntu wekan.caddy[6107]: MONGODB_BIND_UNIX_SOCKET=/var/snap/wekan/222/share (default value)
Jun 28 18:59:30 ubuntu wekan.wekan[6121]: MONGODB_BIND_UNIX_SOCKET=/var/snap/wekan/222/share (default value)
Jun 28 18:59:30 ubuntu wekan.mongodb[6120]: MONGODB_BIND_UNIX_SOCKET=/var/snap/wekan/222/share (default value)
Jun 28 18:59:30 ubuntu wekan.caddy[6107]: MONGODB_BIND_IP= (default value)
Jun 28 18:59:30 ubuntu wekan.mongodb[6120]: MONGODB_BIND_IP= (default value)
Jun 28 18:59:30 ubuntu wekan.wekan[6121]: MONGODB_BIND_IP= (default value)
Jun 28 18:59:30 ubuntu wekan.caddy[6107]: MONGODB_PORT=27019 (default value)
Jun 28 18:59:30 ubuntu wekan.mongodb[6120]: MONGODB_PORT=27019 (default value)
Jun 28 18:59:30 ubuntu wekan.wekan[6121]: MONGODB_PORT=27019 (default value)
Jun 28 18:59:30 ubuntu wekan.caddy[6107]: MAIL_URL=smtp://user:pass@mailserver.examples.com:25/ (default value)
Jun 28 18:59:30 ubuntu wekan.mongodb[6120]: MAIL_URL=smtp://user:pass@mailserver.examples.com:25/ (default value)
Jun 28 18:59:30 ubuntu wekan.caddy[6107]: MAIL_FROM=wekan-admin@example.com (default value)
Jun 28 18:59:30 ubuntu wekan.wekan[6121]: MAIL_URL=smtp://user:pass@mailserver.examples.com:25/ (default value)
Jun 28 18:59:30 ubuntu wekan.mongodb[6120]: MAIL_FROM=wekan-admin@example.com (default value)
Jun 28 18:59:30 ubuntu wekan.caddy[6107]: ROOT_URL=http://10.6.64.74/
Jun 28 18:59:30 ubuntu wekan.mongodb[6120]: ROOT_URL=http://10.6.64.74/
Jun 28 18:59:30 ubuntu wekan.wekan[6121]: MAIL_FROM=wekan-admin@example.com (default value)
Jun 28 18:59:30 ubuntu wekan.caddy[6107]: PORT=80
Jun 28 18:59:30 ubuntu wekan.mongodb[6120]: PORT=80
Jun 28 18:59:30 ubuntu wekan.wekan[6121]: ROOT_URL=http://10.6.64.74/
Jun 28 18:59:30 ubuntu wekan.wekan[6121]: PORT=80
Jun 28 18:59:30 ubuntu wekan.caddy[6107]: DISABLE_MONGODB=false (default value)
Jun 28 18:59:30 ubuntu wekan.mongodb[6120]: DISABLE_MONGODB=false (default value)
Jun 28 18:59:30 ubuntu wekan.caddy[6107]: CADDY_ENABLED=false (default value)
Jun 28 18:59:30 ubuntu wekan.wekan[6121]: DISABLE_MONGODB=false (default value)
Jun 28 18:59:30 ubuntu wekan.caddy[6107]: CADDY_BIND_PORT=3001 (default value)
Jun 28 18:59:30 ubuntu wekan.caddy[6107]: caddy is disabled. Stop service
Jun 28 18:59:30 ubuntu wekan.mongodb[6120]: CADDY_ENABLED=false (default value)
Jun 28 18:59:30 ubuntu wekan.wekan[6121]: CADDY_ENABLED=false (default value)
Jun 28 18:59:31 ubuntu wekan.wekan[6121]: CADDY_BIND_PORT=3001 (default value)
Jun 28 18:59:31 ubuntu wekan.wekan[6121]: MONGO_URL=mongodb:///var/snap/wekan/222/share/mongodb-27019.sock/wekan
Jun 28 18:59:31 ubuntu wekan.mongodb[6120]: CADDY_BIND_PORT=3001 (default value)
Jun 28 18:59:31 ubuntu wekan.mongodb[6120]: mongodb bind options:  --unixSocketPrefix  /var/snap/wekan/222/share --port 27019
Jun 28 18:59:31 ubuntu systemd[1]: Reloading.
Jun 28 18:59:31 ubuntu systemd[1]: Started ACPI event daemon.
Jun 28 18:59:32 ubuntu systemd[1]: Stopping Service for snap application wekan.caddy...
Jun 28 18:59:32 ubuntu systemd[1]: Stopped Service for snap application wekan.caddy.
Jun 28 18:59:32 ubuntu wekan.wekan[6121]: /snap/wekan/222/programs/server/node_modules/fibers/future.js:313
Jun 28 18:59:32 ubuntu wekan.wekan[6121]: #011#011#011#011#011#011throw(ex);
Jun 28 18:59:32 ubuntu wekan.wekan[6121]: #011#011#011#011#011#011^
Jun 28 18:59:32 ubuntu wekan.wekan[6121]: MongoError: failed to connect to server [/var/snap/wekan/222/share/mongodb-27019.sock:27017] on first connect [MongoError: connect ECONNREFUSED /var/snap/wekan/222/share/mongodb-27019.sock]
Jun 28 18:59:32 ubuntu wekan.wekan[6121]:     at Pool.<anonymous> (/snap/wekan/222/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
Jun 28 18:59:32 ubuntu wekan.wekan[6121]:     at emitOne (events.js:116:13)
Jun 28 18:59:32 ubuntu wekan.wekan[6121]:     at Pool.emit (events.js:211:7)
Jun 28 18:59:32 ubuntu wekan.wekan[6121]:     at Connection.<anonymous> (/snap/wekan/222/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
Jun 28 18:59:32 ubuntu wekan.wekan[6121]:     at Object.onceWrapper (events.js:317:30)
Jun 28 18:59:32 ubuntu wekan.wekan[6121]:     at emitTwo (events.js:126:13)
Jun 28 18:59:32 ubuntu wekan.wekan[6121]:     at Connection.emit (events.js:214:7)
Jun 28 18:59:32 ubuntu wekan.wekan[6121]:     at Socket.<anonymous> (/snap/wekan/222/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
Jun 28 18:59:32 ubuntu wekan.wekan[6121]:     at Object.onceWrapper (events.js:315:30)
Jun 28 18:59:32 ubuntu wekan.wekan[6121]:     at emitOne (events.js:116:13)
Jun 28 18:59:32 ubuntu systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, status=1/FAILURE
Jun 28 18:59:32 ubuntu systemd[1]: snap.wekan.wekan.service: Unit entered failed state.
Jun 28 18:59:32 ubuntu systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
Jun 28 18:59:32 ubuntu systemd[1]: snap.wekan.wekan.service: Service hold-off time over, scheduling restart.
Jun 28 18:59:32 ubuntu systemd[1]: Stopped Service for snap application wekan.wekan.
Jun 28 18:59:32 ubuntu systemd[1]: Started Service for snap application wekan.wekan.
Jun 28 18:59:32 ubuntu wekan.wekan[6366]: MONGODB_BIND_UNIX_SOCKET=/var/snap/wekan/222/share (default value)
Jun 28 18:59:32 ubuntu wekan.wekan[6366]: MONGODB_BIND_IP= (default value)
Jun 28 18:59:33 ubuntu wekan.wekan[6366]: MONGODB_PORT=27019 (default value)
Jun 28 18:59:33 ubuntu wekan.wekan[6366]: MAIL_URL=smtp://user:pass@mailserver.examples.com:25/ (default value)
Jun 28 18:59:33 ubuntu wekan.wekan[6366]: MAIL_FROM=wekan-admin@example.com (default value)
Jun 28 18:59:33 ubuntu wekan.wekan[6366]: ROOT_URL=http://10.6.64.74/
Jun 28 18:59:33 ubuntu wekan.wekan[6366]: PORT=80
Jun 28 18:59:33 ubuntu wekan.wekan[6366]: DISABLE_MONGODB=false (default value)
Jun 28 18:59:33 ubuntu wekan.wekan[6366]: CADDY_ENABLED=false (default value)
Jun 28 18:59:33 ubuntu wekan.wekan[6366]: CADDY_BIND_PORT=3001 (default value)
Jun 28 18:59:33 ubuntu wekan.wekan[6366]: MONGO_URL=mongodb:///var/snap/wekan/222/share/mongodb-27019.sock/wekan
Jun 28 18:59:33 ubuntu kernel: [  688.332919] audit_printk_skb: 15 callbacks suppressed
Jun 28 18:59:33 ubuntu kernel: [  688.332922] audit: type=1400 audit(1530205173.388:94): apparmor="DENIED" operation="open" profile="snap.wekan.mongodb" name="/sys/block/" pid=6330 comm="mongod" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jun 28 18:59:34 ubuntu wekan.wekan[6366]: Presence started serverId=taRqfxLc3hibmEp9f
Jun 28 18:59:34 ubuntu wekan.wekan[6366]: Note: you are using a pure-JavaScript implementation of bcrypt.
Jun 28 18:59:34 ubuntu wekan.wekan[6366]: While this implementation will work correctly, it is known to be
Jun 28 18:59:34 ubuntu wekan.wekan[6366]: approximately three times slower than the native implementation.
Jun 28 18:59:34 ubuntu wekan.wekan[6366]: In order to use the native implementation instead, run
Jun 28 18:59:34 ubuntu wekan.wekan[6366]:   meteor npm install --save bcrypt
Jun 28 18:59:34 ubuntu wekan.wekan[6366]: in the root directory of your application.
```

Regards
