### ISSUE TITLE
TypeError: Checklists.foreach

### ISSUE THREAD

**Issue by Jubi94** [wekan/wekan-snap#51]
Hello,

I've followed the installation steps for snap on debian 9 but I still can't access Wekan. 

`journalctl -u snap.wekan.wekan` shows me the following log for Wekan.

```
Jun 28 10:44:33 kanban-demo wekan.wekan[10969]: > Starting add-checklist-items migration.
Jun 28 10:44:34 kanban-demo wekan.wekan[10969]: /snap/wekan/220/programs/server/node_modules/fibers/future.js:280
Jun 28 10:44:34 kanban-demo wekan.wekan[10969]:                                                 throw(ex);
Jun 28 10:44:34 kanban-demo wekan.wekan[10969]:                                                 ^
Jun 28 10:44:34 kanban-demo wekan.wekan[10969]: TypeError: Checklists.forEach is not a function
Jun 28 10:44:34 kanban-demo wekan.wekan[10969]:     at Object.Migrations.add [as migrationCallback] (server/migrations.js:192:14)
Jun 28 10:44:34 kanban-demo wekan.wekan[10969]:     at packages/idmontie_migrations.js:238:17
Jun 28 10:44:34 kanban-demo wekan.wekan[10969]:     at Function.time (/snap/wekan/220/programs/server/profile.js:309:28)
Jun 28 10:44:34 kanban-demo wekan.wekan[10969]:     at /snap/wekan/220/programs/server/boot.js:423:13
Jun 28 10:44:34 kanban-demo wekan.wekan[10969]:     at /snap/wekan/220/programs/server/boot.js:464:5
Jun 28 10:44:34 kanban-demo wekan.wekan[10969]:     at Function.run (/snap/wekan/220/programs/server/profile.js:510:12)
Jun 28 10:44:34 kanban-demo wekan.wekan[10969]:     at /snap/wekan/220/programs/server/boot.js:462:11
Jun 28 10:44:34 kanban-demo systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, status=1/FAILURE
Jun 28 10:44:34 kanban-demo systemd[1]: snap.wekan.wekan.service: Unit entered failed state.
Jun 28 10:44:34 kanban-demo systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.

**Comment by xet7** [comment]
@Jubi94 

Please update your snap to newest Wekan v1.09:
```
sudo snap refresh
```

**Comment by Jubi94** [comment]
@xet7 

v1.09 is already installed

**Comment by xet7** [comment]
@Jubi94 

Thanks ! I will release fixed v1.10 soon.

**Comment by Jubi94** [comment]
@xet7 
Thanks!

**Comment by xet7** [comment]
@Jubi94 

Please try Wekan v1.10, is this fixed now:
```
sudo snap refresh
```

**Comment by Jubi94** [comment]
@xet7 
yes it's fixed. Thank you.
