### ISSUE TITLE
Cant define ldap_fullname_field value for snap (and connexion impossible)

### ISSUE THREAD

**Issue by GuiGuiSoft** [wekan/wekan-snap#68]
Hello,

I can't connect anymore to Wekan 1.74.1 because it tries to get the fullname from LDAP whereas I did not define the field. Where can we find the setting name for snap ?

`sudo snap set wekan ldap-fullname-field="CN"` doesn't work :/

/var/log/messages when I try to connect :
```
Nov 20 11:24:27 MyMachine wekan.wekan[6224]: [WARN] Lookup for unset variable: LDAP_FULLNAME_FIELD
Nov 20 11:24:27 MyMachine wekan.wekan[6224]: [WARN] Lookup for unset variable: LDAP_FULLNAME_FIELD
Nov 20 11:24:27 MyMachine wekan.wekan[6224]: Exception while invoking method 'login' TypeError: Cannot read property 'indexOf' of undefined
Nov 20 11:24:27 MyMachine wekan.wekan[6224]:     at getLdapFullname (packages/wekan:wekan-ldap/server/sync.js:76:21)
Nov 20 11:24:27 MyMachine wekan.wekan[6224]:     at syncUserData (packages/wekan:wekan-ldap/server/sync.js:230:21)
Nov 20 11:24:27 MyMachine wekan.wekan[6224]:     at DDPCommon.MethodInvocation.<anonymous> (packages/wekan:wekan-ldap/server/loginHandler.js:136:5)
Nov 20 11:24:27 MyMachine wekan.wekan[6224]:     at packages/accounts-base/accounts_server.js:468:32
Nov 20 11:24:27 MyMachine wekan.wekan[6224]:     at tryLoginMethod (packages/accounts-base/accounts_server.js:245:14)
Nov 20 11:24:27 MyMachine wekan.wekan[6224]:     at AccountsServer.Ap._runLoginHandlers (packages/accounts-base/accounts_server.js:465:18)
Nov 20 11:24:27 MyMachine wekan.wekan[6224]:     at DDPCommon.MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:528:27)
Nov 20 11:24:27 MyMachine wekan.wekan[6224]:     at packages/check.js:128:16
Nov 20 11:24:27 MyMachine wekan.wekan[6224]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Nov 20 11:24:27 MyMachine wekan.wekan[6224]:     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
Nov 20 11:24:27 MyMachine wekan.wekan[6224]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
Nov 20 11:24:27 MyMachine wekan.wekan[6224]:     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
Nov 20 11:24:27 MyMachine wekan.wekan[6224]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Nov 20 11:24:27 MyMachine wekan.wekan[6224]:     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
Nov 20 11:24:27 MyMachine wekan.wekan[6224]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Nov 20 11:24:27 MyMachine wekan.wekan[6224]:     at Promise (packages/ddp-server/livedata_server.js:715:46)
```

EDIT : I did a snap revert to be able to use again Wekan. If someone know how to disable automatic snap refresh until this bug is solved, I am very interressed :)

Regards.

**Comment by xet7** [comment]
Yes, because it's not it v1.74.1. It's in v1.76 or newer that is currently building, then it will be pushed to snap store.
https://github.com/wekan/wekan/blob/devel/snap-src/bin/config#L251

You see current snap store version at https://snapcraft.io/wekan

When you get new version, you can use:
```
sudo snap set wekan ldap-fullname-field='CN'
```
