### ISSUE TITLE
Latest snap fails at startup (Ubuntu 18.10)

### ISSUE THREAD

**Issue by rishispeets** [wekan/wekan-snap#74]
# Expected Behavior

The latest 2.0 snap package should start up without a problem.

# Current Behavior

When trying to start the snap, initialization logs are visible in a terminal window up to the database connection, after which the terminal window closes without the application starting up.

# Failure Information 

It seems there's a problem initializing or connecting to the mongodb database. Here's the error (full trace in Failure Logs): 

```
MONGO_URL=mongodb:///var/snap/wekan/current/share/mongodb-27019.sock/wekan

/snap/wekan/380/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
MongoError: failed to connect to server [/var/snap/wekan/current/share/mongodb-27019.sock:27017] on first connect [MongoError: connect EACCES /var/snap/wekan/current/share/mongodb-27019.sock]
    at Pool.<anonymous> (/snap/wekan/380/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
```

## Steps to Reproduce

1. Install latest 2.0 snap from snapcraft.io or Ubuntu software center.
2. Start snap.
3. Startup fails.

## Context

* Snap version: 2.36.3
* Operating System: Ubuntu 18.10
* Kernel version: 4.18.0-13-generic

### Full stack trace
```
/snap/wekan/380/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
MongoError: failed to connect to server [/var/snap/wekan/current/share/mongodb-27019.sock:27017] on first connect [MongoError: connect EACCES /var/snap/wekan/current/share/mongodb-27019.sock]
    at Pool.<anonymous> (/snap/wekan/380/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/snap/wekan/380/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/snap/wekan/380/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
```

### Full initialization log before error
```
MONGODB_BIND_UNIX_SOCKET=/var/snap/wekan/current/share (default value)
MONGODB_BIND_IP=127.0.0.1 (default value)
MONGODB_PORT=27019 (default value)
MAIL_URL=smtp://user:pass@mailserver.examples.com:25/ (default value)
MAIL_FROM=wekan-admin@example.com (default value)
ROOT_URL=http://127.0.0.1 (default value)
PORT=8080 (default value)
DISABLE_MONGODB=false (default value)
CADDY_ENABLED=false (default value)
CADDY_BIND_PORT=3001 (default value)
WITH_API=true (default value)
CORS= (default value)
MATOMO_ADDRESS= (default value)
MATOMO_SITE_ID= (default value)
MATOMO_DO_NOT_TRACK=true (default value)
MATOMO_WITH_USERNAME=false (default value)
BROWSER_POLICY_ENABLED=true (default value)
TRUSTED_URL= (default value)
WEBHOOKS_ATTRIBUTES= (default value)
OAUTH2_ENABLED=false (default value)
OAUTH2_CLIENT_ID= (default value)
OAUTH2_SECRET= (default value)
OAUTH2_SERVER_URL= (default value)
OAUTH2_AUTH_ENDPOINT= (default value)
OAUTH2_USERINFO_ENDPOINT= (default value)
OAUTH2_TOKEN_ENDPOINT= (default value)
LDAP_ENABLE=false (default value)
LDAP_PORT=389 (default value)
LDAP_HOST= (default value)
LDAP_BASEDN= (default value)
LDAP_LOGIN_FALLBACK=false (default value)
LDAP_RECONNECT=true (default value)
LDAP_TIMEOUT=10000 (default value)
LDAP_IDLE_TIMEOUT=10000 (default value)
LDAP_CONNECT_TIMEOUT=10000 (default value)
LDAP_AUTHENTIFICATION=false (default value)
LDAP_AUTHENTIFICATION_USERDN= (default value)
LDAP_AUTHENTIFICATION_PASSWORD= (default value)
LDAP_LOG_ENABLED=false (default value)
LDAP_BACKGROUND_SYNC=false (default value)
LDAP_BACKGROUND_SYNC_INTERVAL=100 (default value)
LDAP_BACKGROUND_SYNC_KEEP_EXISTANT_USERS_UPDATED=false (default value)
LDAP_BACKGROUND_SYNC_IMPORT_NEW_USERS=false (default value)
LDAP_ENCRYPTION=false (default value)
LDAP_CA_CERT= (default value)
LDAP_REJECT_UNAUTHORIZED=false (default value)
LDAP_USER_SEARCH_FILTER= (default value)
LDAP_USER_SEARCH_SCOPE= (default value)
LDAP_USER_SEARCH_FIELD= (default value)
LDAP_SEARCH_PAGE_SIZE=0 (default value)
LDAP_SEARCH_SIZE_LIMIT=0 (default value)
LDAP_GROUP_FILTER_ENABLE=false (default value)
LDAP_GROUP_FILTER_OBJECTCLASS= (default value)
LDAP_GROUP_FILTER_GROUP_ID_ATTRIBUTE= (default value)
LDAP_GROUP_FILTER_GROUP_MEMBER_ATTRIBUTE= (default value)
LDAP_GROUP_FILTER_GROUP_MEMBER_FORMAT= (default value)
LDAP_GROUP_FILTER_GROUP_NAME= (default value)
LDAP_UNIQUE_IDENTIFIER_FIELD= (default value)
LDAP_UTF8_NAMES_SLUGIFY=true (default value)
LDAP_USERNAME_FIELD= (default value)
LDAP_FULLNAME_FIELD= (default value)
LDAP_MERGE_EXISTING_USERS=false (default value)
LDAP_SYNC_USER_DATA=false (default value)
LDAP_SYNC_USER_DATA_FIELDMAP= (default value)
LDAP_SYNC_GROUP_ROLES= (default value)
LDAP_DEFAULT_DOMAIN= (default value)
LOGOUT_WITH_TIMER=false (default value)
LOGOUT_IN= (default value)
LOGOUT_ON_HOURS= (default value)
LOGOUT_ON_MINUTES= (default value)
DEFAULT_AUTHENTICATION_METHOD= (default value)
MONGO_URL=mongodb:///var/snap/wekan/current/share/mongodb-27019.sock/wekan
```

**Comment by xet7** [comment]
Do you have MongoDB running?
```
sudo snap start wekan.mongodb
sudo snap enable wekan.mongodb
```

**Comment by xet7** [comment]
What snap services are running?
```
sudo snap services
```

**Comment by xet7** [comment]
I'll install Ubuntu 18.10 to VM and try to reproduce this. I do have Wekan v2.00 snap working on Linux Mint 19.1.

**Comment by xet7** [comment]
I installed Ubuntu 18.10 and latest updates to it and rebooted. Then I did:
```
sudo snap install wekan
sudo snap set wekan root-url='http://localhost'
sudo snap set wekan port='80'
```
And Wekan works on http://localhost using Firefox. I did not see any errors.

**Comment by xet7** [comment]
You could try to reboot, do backup if you have any data in wekan, and then then do:
```
sudo snap remove wekan
sudo snap install wekan
```

**Comment by xet7** [comment]
If you still have problems after those changes above, please reopen issue with more details.
