### ISSUE TITLE
Error: no hostname or hostnames provided in connection string

### ISSUE THREAD

**Issue by mzch** [wekan/wekan-snap#75]
On Debian 9 (stretch) I installed Wekan as the wiki says, https://github.com/wekan/wekan-snap/wiki/Install .
But doesn't start. I found error logs as below:

```
Jan 18 06:47:00 m12 wekan.wekan[6573]: /snap/wekan/381/programs/server/node_modules/fibers/future.js:280
Jan 18 06:47:00 m12 wekan.wekan[6573]: #011#011#011#011#011#011throw(ex);
Jan 18 06:47:00 m12 wekan.wekan[6573]: #011#011#011#011#011#011^
Jan 18 06:47:00 m12 wekan.wekan[6573]: Error: no hostname or hostnames provided in connection string
Jan 18 06:47:00 m12 wekan.wekan[6573]:     at module.exports (/snap/wekan/381/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/url_parser.js:23:11)
Jan 18 06:47:00 m12 wekan.wekan[6573]:     at connect (/snap/wekan/381/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:486:16)
Jan 18 06:47:00 m12 wekan.wekan[6573]:     at Function.MongoClient.connect (/snap/wekan/381/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:250:3)
Jan 18 06:47:00 m12 wekan.wekan[6573]:     at new MongoConnection (packages/mongo/mongo_driver.js:168:11)
Jan 18 06:47:00 m12 wekan.wekan[6573]:     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
Jan 18 06:47:00 m12 wekan.wekan[6573]:     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
Jan 18 06:47:00 m12 wekan.wekan[6573]:     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
Jan 18 06:47:00 m12 wekan.wekan[6573]:     at new Mongo.Collection (packages/mongo/collection.js:99:40)
Jan 18 06:47:00 m12 wekan.wekan[6573]:     at packages/idmontie_migrations.js:38:15
Jan 18 06:47:00 m12 wekan.wekan[6573]:     at packages/idmontie_migrations.js:255:4
Jan 18 06:47:00 m12 systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, status=1/FAILURE
Jan 18 06:47:00 m12 systemd[1]: snap.wekan.wekan.service: Unit entered failed state.
Jan 18 06:47:00 m12 systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
```

What should I do next?

**Comment by xet7** [comment]
Maybe MongoDB is not running?
```
sudo snap start wekan.mongodb
```

**Comment by mzch** [comment]
mongodb started, but immediately terminated.

```
Jan 18 16:50:02 m12 systemd[1]: snap.wekan.mongodb.service: Service hold-off time over, sc
heduling restart.
Jan 18 16:50:02 m12 systemd[1]: Stopped Service for snap application wekan.mongodb.
Jan 18 16:50:02 m12 systemd[1]: snap.wekan.mongodb.service: Start request repeated too qui
ckly.
Jan 18 16:50:02 m12 systemd[1]: Failed to start Service for snap application wekan.mongodb
.
Jan 18 16:50:02 m12 systemd[1]: snap.wekan.mongodb.service: Unit entered failed state.
Jan 18 16:50:02 m12 systemd[1]: snap.wekan.mongodb.service: Failed with result 'exit-code'
```

**Comment by mzch** [comment]
after exec ```sudo mkdir  /var/snap/wekan/current/share```
then mongodb started.

**Comment by xet7** [comment]
Well, for next I would have suggested reboot, and then remove and install wekan again, but seems that creating that share directory works too. I think normally it's created while installing.

**Comment by mzch** [comment]
and then exec ```systemctl start snap.wekan.wekan```, and wekan started. Why wekan doesn't start unless starting mongodb?

**Comment by xet7** [comment]
All Wekan data is saved to MongoDB. Wekan does not save data anywhere else, and does not work without MongoDB.

Usually wekan starts immediately after installing:
```
sudo snap install wekan
```

**Comment by xet7** [comment]
To set Wekan as service, it should be enough to:
```
sudo snap enable wekan
```
But really if someone has really made sure that for example mongodb does not start
```
sudo snap stop wekan.mongodb
sudo snap disable wekan.mongodb
sudo systemctl stop snap.wekan.mongodb
sudo systemctl disable snap.wekan.mongodb
```
The all those need to be started and enabled. There is wekan/mongodb/caddy parts of Wekan snap, and each of them can be enabled and disabled separately. For example, use only caddy, wekan with some elsewhere installed mongodb (with optional authentication), or use only mongodb, or any combination of them.

**Comment by mzch** [comment]
Thanks, I reinstalled Wekan, and it's all right. Thanks!
